### ISSUE TITLE
Please delete VMob SDK repository

### ISSUE THREAD

**Issue by FrancoSabadini** [daoyin/learngit#1]
Hi @daoyin, as I wrote on the pull request I created on the vmob-android-sdk project (https://github.com/daoyin/vmob-android-sdk), I am working for VMob as a mobile team lead, and we need you to delete the VMob SDK repository under your username as it could contain sensitive information about our SDK. If this is not taken care of soon I'll have to file a complaint with Github but I'd rather not do that so please delete it as soon as you can. Cheers.

PS: I'm creating this issue here cause the vmob-android-sdk project doesn't have the issues section enabled.

**Comment by daoyin** [comment]
I have already deleted the repository.

Cheers,
Dao

2015-11-11 11:53 GMT+13:00 Franco Sabadini <notifications@github.com>:

> Hi @daoyin <https://github.com/daoyin>, as I wrote on the pull request I
> created on the vmob-android-sdk project (
> https://github.com/daoyin/vmob-android-sdk), I am working for VMob as a
> mobile team lead, and we need you to delete the VMob SDK repository under
> your username as it could contain sensitive information about our SDK. If
> this is not taken care of soon I'll have to file a complain with Github but
> I'd rather not do that so please delete it as soon as you can. Cheers.
>
> PS: I'm creating this issue here cause the vmob-android-sdk project
> doesn't have the issues section enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daoyin/learngit/issues/1>.
>



-- 
Kind Regards,
Dao Yin

**Comment by FrancoSabadini** [comment]
Awesome, thanks @daoyin! :)
